name: Secrets example
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "This varaible should be hidden"
          echo ${{ secrets.MY_EQIX_VAR1 }}
          echo "This hack to read my variable"
          echo ${{ secrets.MY_EQIX_VAR1 }} | sed 's/./& /g'
          
      - run: ls /home/runner/work/selenium
          
      - run: ls /home/runner/work/selenium/selenium

